// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "email": "your@mail.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/book": {
			"get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Book"
                ],
                "summary": "Get all books",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Book"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Book"
                ],
                "summary": "create a new book",
                "parameters": [
                    {
                        "description": "Request",
                        "name": "Request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/exampleRequest/models.Book"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/exampleRequest/models.Book"
                        }
                    }
                }
            }
        },

        "/auth": {
            "post": {
                "description": "Get Token.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Token"
                ],
                "summary": "get token",
				"parameters": [
                    {
                        "description": "Request",
                        "name": "Request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/exampleRequest/models.Auth"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.Book": {
            "type": "object",
            "required": [
                "author",
                "description",
                "rating",
                "id",
                "title"
            ],
            "properties": {
				"id": {
                    "type": "integer"
                },
				"title": {
                    "type": "string",
                    "maxLength": 255
                },
				"description": {
                    "type": "string"
                },
                "author": {
                    "type": "string",
                    "maxLength": 255
                },
				"created_at": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "rating": {
                    "$ref": "#/definitions/models.BookRating"
                }
            }
        },
        "models.BookRating": {
            "type": "object",
            "properties": {
				"id": {
                    "type": "integer"
                },
				"id_buku": {
                    "type": "integer"
                },
                "picture": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "rating": {
                    "type": "integer",
                    "maximum": 5,
                    "minimum": 1
                }
            }
        }
    },
	"exampleRequest": {
		"models.Book": {
            "type": "object",
            "required": [
                "title",
                "description",
				"author"
            ],
            "properties": {
				"title": {
                    "type": "string",
                    "maxLength": 255
                },
				"description": {
                    "type": "string"
                },
                "author": {
                    "type": "string",
                    "maxLength": 255
                }
            }
        },
		"models.Book.Delete": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
				"id": {
                    "type": "integer"
                }
            }
        },
		"models.Auth": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
				"email": {
                    "type": "string"
                },
				"password": {
                    "type": "string"
                }
            }
        }
	},
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "API",
	Description:      "This is an auto-generated API Docs.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
